### ISSUE TITLE
A naive question: what means rcc dump

### ISSUE THREAD

**Issue by LittleNewton** [avatartwo/avatar2#111]
I want to know `rcc_dump` mean what.

There is no code comment.

Thanks.

**Comment by aurelf** [comment]
Hi, 
RCC refers to Reset and Clock Control. Datasheet of the STM32L152RE confirms the address range: 
![Capture d’écran_2022-09-01_17-19-34](https://user-images.githubusercontent.com/698620/187951709-495b6bbc-d620-4fb8-8950-3992eeb1b26f.png)

The reference manual (RM0038) has more details in "Section 6 Reset and clock control (RCC)"
