### ISSUE TITLE
target.cont() function can't successfully continue target when it run in the watchmen callback

### ISSUE THREAD

**Issue by hexinglu** [avatartwo/avatar2#15]
I want to hook a function by using breakpoint and watchmen in avatar2. Then, I find that I can cont() the breakpoint in main function, but in watchmen callback, it has some issues. When I debug avatar2, I find cont() from watchmen callback will reach the code /avatar2/avatar2/targets/target.py line 77: state_reached.wait() and suspended with the variable state_reached._Event__flag = false. But, cont() in main at this code has the variable state_reached._Event__flag = true. Then, I don't debug in the threading.pyi. I find if blocking is True, the avatar2 will not in this wait() function. But, I find target.cont() will not pass the blocking information to this part. Than, I change the code in /avatar2/avatar2/targets/gdb_target.py line 82: from super(GDBTarget, self).cont() to super(GDBTarget, self).cont(blocking=blocking). And fix this problem. Hope it's useful for you. Have a nice day,

**Comment by mariusmue** [comment]
Thanks for reporting! I integrated this change with acfe4efc95ec5384de6c1d4469ea6449ae998bfc.
