### ISSUE TITLE
[error] error: can't copy 'src/build/llvm/lib/libkeystone.so': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by ZakiG** [avatartwo/avatar2#23]
When I use pip to install avatar2, I got this error:
`    llvm/keystone/CMakeFiles/keystone.dir/build.make:1814: recipe for target 'llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp.o' failed
    make[2]: *** [llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp.o] Error 4
    make[2]: *** 正在等待未完成的任务....
    CMakeFiles/Makefile2:405: recipe for target 'llvm/keystone/CMakeFiles/keystone.dir/all' failed
    make[1]: *** [llvm/keystone/CMakeFiles/keystone.dir/all] Error 2
    Makefile:151: recipe for target 'all' failed
    make: *** [all] Error 2
    running install_lib
    running install_data
    error: can't copy 'src/build/llvm/lib/libkeystone.so': doesn't exist or not a regular file
`
Than , I try to build avatar2 manually,  but when I use  `sudo python setup.py install`,  I got this error:
`Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
llvm/keystone/CMakeFiles/keystone.dir/build.make:1814: recipe for target 'llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp.o' failed
make[2]: *** [llvm/keystone/CMakeFiles/keystone.dir/__/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp.o] Error 4
make[2]: *** 正在等待未完成的任务....
CMakeFiles/Makefile2:405: recipe for target 'llvm/keystone/CMakeFiles/keystone.dir/all' failed
make[1]: *** [llvm/keystone/CMakeFiles/keystone.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
error: Setup script exited with error: can't copy 'src/build/llvm/lib/libkeystone.so': doesn't exist or not a regular file
`
I believe I have installed  all dependencies. So,  how can I solve these problems.  Thanks

**Comment by mariusmue** [comment]
Hi there! 
Sorry for the inconvenience, but the problem is not directly related to avatar², but instead [keystone](http://www.keystone-engine.org/), one of its dependencies.
This is similar to #22.

For now, I recommend building keystone from it's source, which should work with the following commands.
```
$ git clone https://github.com/keystone-engine/keystone.git
$ cd keystone
$ mkdir build
$ cd build
$ ../make-share.sh
$ sudo make install
$ sudo ldconfig
$ cd ../bindings/python
$ sudo make install3 # or sudo make install for python2-bindings
```
