### ISSUE TITLE
Which address do I need？

### ISSUE THREAD

**Issue by DerZc** [avatartwo/avatar2#26]
When I use avater to run a firmware, which address do I need in add_memory_range.

**Comment by mariusmue** [comment]
That depends on the kind of device/firmware you have, and a generic answer is impossible here.

You can figure out the memory mapping by reverse engineering, consulting the data sheet, or even by using avatar² iteratively in connection to a physical device.

**Comment by DerZc** [comment]
I got it, thank you very much!
