### ISSUE TITLE
Could we only use one OpenOCD target to get the mmio in avatar2?

### ISSUE THREAD

**Issue by DarknessChen** [avatartwo/avatar2#59]
I want to get the mmio recordings while the board is running (instead of doing the rehosting, the binary is actually running on the mcu chip). Is it possible to get the mmio (read/write) traffics by using avatar2? I modify some codes of pretender (e.g. make the memory map but set the `forwarded` argument of `add_memory_range` to `false`), however, there is no recordings in the output file, so I wonder whether it is possible to get the recordings by only using OpenOCD target.

Thanks!

**Comment by mariusmue** [comment]
Heya,
The recording/logging of MMIO is based on the fact that MMIO accesses are made *via* avatar2.
Remote Memory Requests are emitted by one target and send to avatar2, which then logs them and forwards it to the according target.

Hence, avatar2 can currently not log MMIO accesses if they just happen local on the device.

I think the best way to get those accesses is collecting ETM traces on the board itself, but it requires support from the hardware side and an according debugger.

**Comment by DarknessChen** [comment]
This solves my problem. Thanks a lot @mariusmue ! I think Avatar2 is a really good community:)
