### ISSUE TITLE
Dependency problem pygdbmi

### ISSUE THREAD

**Issue by icemonster** [avatartwo/avatar2#61]
Avatar2 breaks with the new version of pygdbmi (0.10.0.0).
Installing this on ubuntu >= 19 seems to yield an error when running the "Hello world" example in the tests folder.

After installing a previous version of pygdbmi, everything runs smoothly
`python3 -m pip pygdbmi==0.9.0.2`

**Comment by mariusmue** [comment]
Which version of Python, and which version avatar2 were you using when encountering this problem?

Did you test if the problem persists with git-master of avatar2?
Background is, we recently merged #32 which should fix the issue - but didn't update the version on PyPi yet.

**Comment by mariusmue** [comment]
Can not reproduce with current master version of avatar2, and no further comments where given here. I'll close this for now, if the problem persist, please let us know!
